apis:
  OpenProductionDataIO@v0:
    root: opdio.yml
    extends:
      - recommended
    rules:
      tag-description: off
      operation-summary: off
      no-unresolved-refs: off
      no-unused-components: off
      operation-2xx-response: error
      operation-operationId: error
      operation-singular-tag: error
      no-enum-type-mismatch: error
      no-identical-paths: error
      no-ambiguous-paths: error
